apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment-strategy
  name: nginx-deployment-strategy
spec:
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deployment-strategy
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
      # Ou por porcentagem
      # maxSurge: 10%
      # maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nginx-deployment-strategy
    spec:
      containers:
      - name: nginx
        #image: nginx:1.16.0
        image: nginx:1.15.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "300m"
          limits:
            memory: "128Mi"
            cpu: "600m"
