- name: Preparar todos os nós (Common)
  hosts: all
  become: yes
  tasks:
    - name: Desabilitar Swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Carregar módulos do Kernel
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
    
    - name: Ativar módulos agora
      shell: modprobe overlay && modprobe br_netfilter

    - name: Configurar Sysctl para K8s
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
      register: sysctl_conf

    - name: Aplicar Sysctl
      command: sysctl --system
      when: sysctl_conf.changed

    - name: Instalar dependências básicas
      apt:
        pkg: [apt-transport-https, ca-certificates, curl, gpg, lsb-release]
        update_cache: yes

    # --- Containerd ---
    - name: Adicionar chave GPG do Docker
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes

    - name: Adicionar repositório Docker
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

    - name: Instalar Containerd
      apt:
        name: containerd.io
        update_cache: yes
    
    - name: Configurar Containerd (SystemdCgroup)
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      notify: Restart Containerd

    # --- Kubeadm/Kubelet ---
    - name: Adicionar chave GPG do Kubernetes
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes

    - name: Adicionar repositório Kubernetes
      shell: |
         echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Instalar Kubeadm, Kubelet, Kubectl
      apt:
        pkg: [kubelet, kubeadm, kubectl]
        update_cache: yes
    
    - name: Segurar versões (apt-mark hold)
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: [kubelet, kubeadm, kubectl]

  handlers:
    - name: Restart Containerd
      service:
        name: containerd
        state: restarted