apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kube-prometheus-demo
  region: sa-east-1
  version: "1.34"
nodeGroups:
  - name: linux-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    ssh:
      allow: false
    tags:
      Environment: production
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest